/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Cafe_Management_System;

import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Random;


/**
 *
 * @author BLACK
 */
public class Cafe_Management_System extends javax.swing.JFrame {
double [] drink =new double[5];
double [] cake =new double[8];
double [] cost =new double[5];
double [] i = new double[15];
    /**
     * Creates new form Cafe_Management_System
     */
    public Cafe_Management_System() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jChkCoffee = new javax.swing.JCheckBox();
        jChkRed = new javax.swing.JCheckBox();
        jChkBlack = new javax.swing.JCheckBox();
        jChkBoston = new javax.swing.JCheckBox();
        jChkCarlton = new javax.swing.JCheckBox();
        jChkLagos = new javax.swing.JCheckBox();
        jChkKilburn = new javax.swing.JCheckBox();
        jChkQueen = new javax.swing.JCheckBox();
        jTextcoffee = new javax.swing.JTextField();
        jTextRed = new javax.swing.JTextField();
        jTextBoston = new javax.swing.JTextField();
        jTextBlack = new javax.swing.JTextField();
        jTextLagos = new javax.swing.JTextField();
        jTextKilburn = new javax.swing.JTextField();
        jTextCarlton = new javax.swing.JTextField();
        jTextQueen = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jChkcup = new javax.swing.JCheckBox();
        jChkIcecup = new javax.swing.JCheckBox();
        jChkIcelat = new javax.swing.JCheckBox();
        jChkEsp = new javax.swing.JCheckBox();
        jChkLat = new javax.swing.JCheckBox();
        jTextCup = new javax.swing.JTextField();
        jTextIceCup = new javax.swing.JTextField();
        jTextIcelat = new javax.swing.JTextField();
        jTextEsp = new javax.swing.JTextField();
        jTextLat = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextmain = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jlblCostDrinks = new javax.swing.JLabel();
        jlblCostCakes = new javax.swing.JLabel();
        jlblService = new javax.swing.JLabel();
        jlblDrinks = new javax.swing.JLabel();
        jlblServices = new javax.swing.JLabel();
        jlblCakes = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTotal = new javax.swing.JButton();
        jReceipt = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jExit = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jlblTax = new javax.swing.JLabel();
        jlblSubTotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jlblTotals = new javax.swing.JLabel();
        jlblTaxes = new javax.swing.JLabel();
        jlblSubTotals = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1368, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkCoffee.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jChkCoffee.setText("Coffee cake");
        jChkCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCoffeeMouseClicked(evt);
            }
        });

        jChkRed.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jChkRed.setText("Red Velvet Cake");
        jChkRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkRedMouseClicked(evt);
            }
        });
        jChkRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkRedActionPerformed(evt);
            }
        });

        jChkBlack.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jChkBlack.setText("Black Forest Cake");
        jChkBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkBlackMouseClicked(evt);
            }
        });

        jChkBoston.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jChkBoston.setText("Boston Cream Pie");
        jChkBoston.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkBostonMouseClicked(evt);
            }
        });

        jChkCarlton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jChkCarlton.setText("Carlton Hill Chocolate Cake");
        jChkCarlton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkCarltonMouseClicked(evt);
            }
        });

        jChkLagos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jChkLagos.setText("Lagos chocolate Cake");
        jChkLagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLagosMouseClicked(evt);
            }
        });

        jChkKilburn.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jChkKilburn.setText("Kilburn Chocolate Cake");
        jChkKilburn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkKilburnMouseClicked(evt);
            }
        });

        jChkQueen.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jChkQueen.setText("Queen's Park Chocolate Cake");
        jChkQueen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkQueenMouseClicked(evt);
            }
        });
        jChkQueen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkQueenActionPerformed(evt);
            }
        });

        jTextcoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextcoffee.setText("0");
        jTextcoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextcoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextcoffeeActionPerformed(evt);
            }
        });

        jTextRed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextRed.setText("0");
        jTextRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRedActionPerformed(evt);
            }
        });

        jTextBoston.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextBoston.setText("0");
        jTextBoston.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextBoston.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBostonActionPerformed(evt);
            }
        });

        jTextBlack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextBlack.setText("0");
        jTextBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBlackActionPerformed(evt);
            }
        });

        jTextLagos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextLagos.setText("0");
        jTextLagos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextLagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLagosActionPerformed(evt);
            }
        });

        jTextKilburn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextKilburn.setText("0");
        jTextKilburn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextKilburn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextKilburnActionPerformed(evt);
            }
        });

        jTextCarlton.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCarlton.setText("0");
        jTextCarlton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextCarlton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCarltonActionPerformed(evt);
            }
        });

        jTextQueen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextQueen.setText("0");
        jTextQueen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextQueen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQueenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jChkCoffee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jChkRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextRed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextcoffee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jChkBoston)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jChkBlack)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jChkLagos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jChkKilburn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jChkQueen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextQueen, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jChkCarlton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextcoffee, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChkCoffee))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkRed)
                    .addComponent(jTextRed, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkBoston)
                    .addComponent(jTextBoston, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkBlack)
                    .addComponent(jTextBlack, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkLagos)
                    .addComponent(jTextLagos, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkKilburn)
                    .addComponent(jTextKilburn, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkCarlton)
                    .addComponent(jTextCarlton, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkQueen)
                    .addComponent(jTextQueen, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 300, 300));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Cafe Management Systems");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 60));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jChkcup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkcup.setText("Cappuccino");
        jChkcup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkcupMouseClicked(evt);
            }
        });

        jChkIcecup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkIcecup.setText("Ice Cappuccino");
        jChkIcecup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcecupMouseClicked(evt);
            }
        });

        jChkIcelat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkIcelat.setText("Iced Lattle");
        jChkIcelat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkIcelatMouseClicked(evt);
            }
        });

        jChkEsp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkEsp.setText("Espresso");
        jChkEsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkEspMouseClicked(evt);
            }
        });

        jChkLat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jChkLat.setText("Lattle");
        jChkLat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jChkLatMouseClicked(evt);
            }
        });
        jChkLat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkLatActionPerformed(evt);
            }
        });

        jTextCup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCup.setText("0");
        jTextCup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextCup.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextCup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCupActionPerformed(evt);
            }
        });

        jTextIceCup.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextIceCup.setText("0");
        jTextIceCup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextIcelat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextIcelat.setText("0");
        jTextIcelat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextEsp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextEsp.setText("0");
        jTextEsp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextLat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextLat.setText("0");
        jTextLat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jTextLat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jChkLat, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jChkIcecup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jChkcup)
                        .addComponent(jChkEsp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jChkIcelat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextCup, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIceCup, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIcelat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextLat, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkcup)
                    .addComponent(jTextCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkIcecup)
                    .addComponent(jTextIceCup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkEsp)
                    .addComponent(jTextEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChkIcelat)
                    .addComponent(jTextIcelat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jChkLat)
                    .addComponent(jTextLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 350, 300));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTextmain.setColumns(20);
        jTextmain.setRows(5);
        jScrollPane1.setViewportView(jTextmain);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 420, 490));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlblCostDrinks.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblCostDrinks.setText("Cost of Drinks");

        jlblCostCakes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblCostCakes.setText("Cost of Cakes");

        jlblService.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlblService.setText("Service Charge");

        jlblDrinks.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jlblDrinks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDrinks.setText("0");
        jlblDrinks.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblServices.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jlblServices.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblServices.setText("1.25");
        jlblServices.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblCakes.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jlblCakes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCakes.setText("0");
        jlblCakes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblCostCakes, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblServices, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCakes, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(43, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jlblCostDrinks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCostDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblCostCakes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCakes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblService, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblServices, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 380, 260));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTotal.setText("Total");
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });

        jReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jReceipt.setText("Receipt");
        jReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReceiptActionPerformed(evt);
            }
        });

        jReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jExit.setText("Exit");
        jExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTotal)
                .addGap(18, 18, 18)
                .addComponent(jReceipt)
                .addGap(18, 18, 18)
                .addComponent(jReset)
                .addGap(18, 18, 18)
                .addComponent(jExit, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotal)
                    .addComponent(jReceipt)
                    .addComponent(jReset)
                    .addComponent(jExit))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 420, 70));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jlblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTax.setText("Tax");

        jlblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotal.setText("Sub Total");

        jlblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotal.setText("Total");

        jlblTotals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTotals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTotals.setText("0");
        jlblTotals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblTaxes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblTaxes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTaxes.setText("0");
        jlblTaxes.setToolTipText("");
        jlblTaxes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblSubTotals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlblSubTotals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSubTotals.setText("0");
        jlblSubTotals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jlblSubTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jlblSubTotals, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblTotals, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                    .addContainerGap(132, Short.MAX_VALUE)
                    .addComponent(jlblTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlblTax)
                .addGap(46, 46, 46)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jlblSubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTotal)
                            .addComponent(jlblTotals, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jlblSubTotals, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jlblTaxes, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(170, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 280, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed
        // TODO add your handling code here:
        drink[0]=Double.parseDouble(jlblDrinks.getText());
        drink[1]=Double.parseDouble(jlblCakes.getText());
        drink[2]=Double.parseDouble(jlblServices.getText());
               
        double cTotal=(drink[0]+drink[1]+drink[2]);
        String iTaxTotal=String.format("$ %.2f", cTotal/100);
        jlblTaxes.setText(iTaxTotal);
        
        double subTotal=cTotal;
        String isubTotal=String.format("$ %.2f", subTotal);
        jlblSubTotals.setText(isubTotal);
        
        double allTotal=cTotal;
        String iTotal=String.format("$ %.2f", allTotal+(allTotal/100));
        jlblTotals.setText(iTotal);
        
        String CostD=String.format("$ %.2f", drink[0]);
        jlblDrinks.setText(CostD);
        String CostC=String.format("$ %.2f", drink[1]);
        jlblCakes.setText(CostC);
        String Service=String.format("$ %.2f", drink[2]);
        jlblServices.setText(Service);
    }//GEN-LAST:event_jTotalActionPerformed

    private void jChkRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkRedActionPerformed

    private void jChkQueenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkQueenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkQueenActionPerformed

    private void jTextCupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCupActionPerformed

    private void jTextLatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLatActionPerformed

    private void jTextcoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextcoffeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextcoffeeActionPerformed

    private void jTextRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRedActionPerformed

    private void jTextBostonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBostonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBostonActionPerformed

    private void jTextBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBlackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBlackActionPerformed

    private void jTextLagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLagosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLagosActionPerformed

    private void jTextKilburnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextKilburnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextKilburnActionPerformed

    private void jTextCarltonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCarltonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCarltonActionPerformed

    private void jTextQueenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQueenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQueenActionPerformed

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        // TODO add your handling code here:
        jlblDrinks.setText(null);
        jlblCakes.setText(null);
        jlblServices.setText(null);
        jlblTaxes.setText(null);
        jlblSubTotals.setText(null);
        jlblTotals.setText(null);
        jTextcoffee.setText(null);
        jTextRed.setText(null);
        jTextBoston.setText(null);
        jTextBlack.setText(null);
        jTextLagos.setText(null);
        jTextKilburn.setText(null);
        jTextCarlton.setText(null);
        jTextQueen.setText(null);
        jChkCoffee.setSelected(false);
        jChkRed.setSelected(false);
        jChkBoston.setSelected(false);
        jChkBlack.setSelected(false);
        jChkLagos.setSelected(false);
        jChkKilburn.setSelected(false);
        jChkCarlton.setSelected(false);
        jChkQueen.setSelected(false);
        jChkcup.setSelected(false);
        jChkIcecup.setSelected(false);
        jChkEsp.setSelected(false);
        jChkIcelat.setSelected(false);
        jChkLat.setSelected(false);
        jTextCup.setText(null);
        jTextIceCup.setText(null);
        jTextEsp.setText(null);
        jTextIcelat.setText(null);
        jTextLat.setText(null);
        jTextmain.setText(null);
    }//GEN-LAST:event_jResetActionPerformed

    private void jExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExitActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jExitActionPerformed

    private void jReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReceiptActionPerformed
        // TODO add your handling code here:
        drink[0]=Double.parseDouble(jTextCup.getText());
        drink[1]=Double.parseDouble(jTextIceCup.getText());
        drink[2]=Double.parseDouble(jTextEsp.getText());
        drink[3]=Double.parseDouble(jTextIcelat.getText());
        drink[4]=Double.parseDouble(jTextLat.getText());
        
        cake[0]=Double.parseDouble(jTextcoffee.getText());
        cake[1]=Double.parseDouble(jTextRed.getText());
        cake[2]=Double.parseDouble(jTextBoston.getText());
        cake[3]=Double.parseDouble(jTextBlack.getText());
        cake[4]=Double.parseDouble(jTextLagos.getText());
        cake[5]=Double.parseDouble(jTextKilburn.getText());
        cake[6]=Double.parseDouble(jTextCarlton.getText());
        cake[7]=Double.parseDouble(jTextQueen.getText());
        
        cost[0]=Double.parseDouble(jlblTaxes.getText());
        cost[1]=Double.parseDouble(jlblSubTotals.getText());
        cost[2]=Double.parseDouble(jlblTotals.getText());
        
        int refs=1325+(int)(Math.random()*4238);
        
        Calendar timer =Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime =new SimpleDateFormat("HH:MM:SS");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate =new SimpleDateFormat("dd-MM-YYYY");
        Tdate.format(timer.getTime());
        
        
        jTextmain.append("\t\n Cafe Management Systems:\n\n"+
                "Reference:\t\t\t"+refs+
                "\n=========================\t"+
                "\nCappuccino\t\t" + drink[0] +
                "\nIceCappuccino\t\t" + drink[1] +
                "\nEspresso\t\t" + drink[2] +
                "\nIceLattle\t\t" + drink[3] +
                "\nLattle\t\t" + drink[4] +
                "\n=========================\t\t"+
                "\nCoffe Cake\t\t" + cake[0]+
                "\nCoffe Red velvet Cake\t\t\t" + cake[1]+
                "\nCoffe Boston Cream Pie\t\t" + cake[2]+
                "\nCoffe Black forest Cake\t\t" + cake[3]+
                "\nCoffe Lagos Chocolate Cake\t\t" + cake[4]+
                "\nCoffe Kilburn Chocolate Cake\t\t" + cake[5]+
                "\nCoffe Carlton hill Chocolate Cake\t" + cake[6]+
                "\nCoffe Queen's park Chocolate Cake\t" + cake[7]+
                "\n===============================\t\t"+
                "\n Tax\t\t" + cost[0]+
                "\n SubTotal\t\t" + cost[1]+
                "\n Total\t\t" + cost[2]+
                "\nDate: "+Tdate.format(timer.getTime())+
                "\nTime: "+tTime.format(timer.getTime())+
                "\n\n\t\tThank You ! come again");
    }//GEN-LAST:event_jReceiptActionPerformed

    private void jChkLatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkLatActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jChkLatActionPerformed

    private void jChkLatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLatMouseClicked
        // TODO add your handling code here:
        double cLattle =Double.parseDouble(jlblDrinks.getText());
        double Lattle=Double.parseDouble(jTextLat.getText());
        double iLattle=1.99;
        if (jChkLat.isSelected())
        {
            i[4]=(Lattle*iLattle)+cLattle;
            String pDrink=String.format("%.2f", i[4]);
            jlblDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkLatMouseClicked

    private void jChkcupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkcupMouseClicked
        double cCappuccino =Double.parseDouble(jlblDrinks.getText());
        double Cappuccino=Double.parseDouble(jTextCup.getText());
        double iCappuccino=2.39;
        if (jChkcup.isSelected())
        {
            i[0]=(Cappuccino*iCappuccino)+cCappuccino;
            String pDrink=String.format("%.2f", i[0]);
            jlblDrinks.setText(pDrink);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jChkcupMouseClicked

    private void jChkIcecupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcecupMouseClicked
        // TODO add your handling code here:
        double cIceCappuccino =Double.parseDouble(jlblDrinks.getText());
        double IceCappuccino=Double.parseDouble(jTextIceCup.getText());
        double iIceCappuccino=1.58;
        if (jChkIcecup.isSelected())
        {
            i[1]=(IceCappuccino*iIceCappuccino)+cIceCappuccino;
            String pDrink=String.format("%.2f", i[1]);
            jlblDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkIcecupMouseClicked

    private void jChkEspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkEspMouseClicked
        // TODO add your handling code here:
        double cEspresso =Double.parseDouble(jlblDrinks.getText());
        double Espresso=Double.parseDouble(jTextEsp.getText());
        double iEspresso=3.39;
        if (jChkEsp.isSelected())
        {
            i[2]=(Espresso*iEspresso)+cEspresso;
            String pDrink=String.format("%.2f", i[2]);
            jlblDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkEspMouseClicked

    private void jChkIcelatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkIcelatMouseClicked
        // TODO add your handling code here:
        double cIceLattle =Double.parseDouble(jlblDrinks.getText());
        double IceLattle=Double.parseDouble(jTextIcelat.getText());
        double iIceLattle=1.59;
        if (jChkIcelat.isSelected())
        {
            i[3]=(IceLattle*iIceLattle)+cIceLattle;
            String pDrink=String.format("%.2f", i[3]);
            jlblDrinks.setText(pDrink);
        }
    }//GEN-LAST:event_jChkIcelatMouseClicked

    private void jChkCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCoffeeMouseClicked
        // TODO add your handling code here:
        double cCoffee =Double.parseDouble(jlblCakes.getText());
        double Coffee=Double.parseDouble(jTextcoffee.getText());
        double iCoffee=2.78;
        if (jChkCoffee.isSelected())
        {
            i[5]=(Coffee*iCoffee)+cCoffee;
            String pCake=String.format("%.2f", i[5]);
            jlblCakes.setText(pCake);
        }
    }//GEN-LAST:event_jChkCoffeeMouseClicked

    private void jChkRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkRedMouseClicked
        // TODO add your handling code here:
        double cRed =Double.parseDouble(jlblCakes.getText());
        double Red=Double.parseDouble(jTextRed.getText());
        double iRed=2.12;
        if (jChkRed.isSelected())
        {
            i[6]=(Red*iRed)+cRed;
            String pCake=String.format("%.2f", i[6]);
            jlblCakes.setText(pCake);
        }
    }//GEN-LAST:event_jChkRedMouseClicked

    private void jChkBostonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkBostonMouseClicked
        // TODO add your handling code here:
        double cBoston =Double.parseDouble(jlblCakes.getText());
        double Boston=Double.parseDouble(jTextBoston.getText());
        double iBoston=3.54;
        if (jChkBoston.isSelected())
        {
            i[7]=(Boston*iBoston)+cBoston;
            String pCake=String.format("%.2f", i[7]);
            jlblCakes.setText(pCake);
        }
    }//GEN-LAST:event_jChkBostonMouseClicked

    private void jChkBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkBlackMouseClicked
        // TODO add your handling code here:
        double cBlack =Double.parseDouble(jlblCakes.getText());
        double Black=Double.parseDouble(jTextBlack.getText());
        double iBlack=3.12;
        if (jChkBlack.isSelected())
        {
            i[8]=(Black*iBlack)+cBlack;
            String pCake=String.format("%.2f", i[8]);
            jlblCakes.setText(pCake);
        }
    }//GEN-LAST:event_jChkBlackMouseClicked

    private void jChkLagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkLagosMouseClicked
        // TODO add your handling code here:
        double cLagos =Double.parseDouble(jlblCakes.getText());
        double Lagos=Double.parseDouble(jTextLagos.getText());
        double iLagos=4.12;
        if (jChkLagos.isSelected())
        {
            i[9]=(Lagos*iLagos)+cLagos;
            String pCake=String.format("%.2f", i[9]);
            jlblCakes.setText(pCake);
        }
    }//GEN-LAST:event_jChkLagosMouseClicked

    private void jChkKilburnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkKilburnMouseClicked
        // TODO add your handling code here:
        double cKilburn =Double.parseDouble(jlblCakes.getText());
        double Kilburn=Double.parseDouble(jTextKilburn.getText());
        double iKilburn=3.78;
        if (jChkKilburn.isSelected())
        {
            i[10]=(Kilburn*iKilburn)+cKilburn;
            String pCake=String.format("%.2f", i[10]);
            jlblCakes.setText(pCake);
        }
    }//GEN-LAST:event_jChkKilburnMouseClicked

    private void jChkCarltonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkCarltonMouseClicked
        // TODO add your handling code here:
        double cCarlton =Double.parseDouble(jlblCakes.getText());
        double Carlton=Double.parseDouble(jTextCarlton.getText());
        double iCarlton=4.74;
        if (jChkCarlton.isSelected())
        {
            i[11]=(Carlton*iCarlton)+cCarlton;
            String pCake=String.format("%.2f", i[11]);
            jlblCakes.setText(pCake);
        }
    }//GEN-LAST:event_jChkCarltonMouseClicked

    private void jChkQueenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jChkQueenMouseClicked
        // TODO add your handling code here:
        double cQueen =Double.parseDouble(jlblCakes.getText());
        double Queen=Double.parseDouble(jTextQueen.getText());
        double iQueen=5.12;
        if (jChkQueen.isSelected())
        {
            i[12]=(Queen*iQueen)+cQueen;
            String pCake=String.format("%.2f", i[12]);
            jlblCakes.setText(pCake);
        }
    }//GEN-LAST:event_jChkQueenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafe_Management_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafe_Management_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jChkBlack;
    private javax.swing.JCheckBox jChkBoston;
    private javax.swing.JCheckBox jChkCarlton;
    private javax.swing.JCheckBox jChkCoffee;
    private javax.swing.JCheckBox jChkEsp;
    private javax.swing.JCheckBox jChkIcecup;
    private javax.swing.JCheckBox jChkIcelat;
    private javax.swing.JCheckBox jChkKilburn;
    private javax.swing.JCheckBox jChkLagos;
    private javax.swing.JCheckBox jChkLat;
    private javax.swing.JCheckBox jChkQueen;
    private javax.swing.JCheckBox jChkRed;
    private javax.swing.JCheckBox jChkcup;
    private javax.swing.JButton jExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jReceipt;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextBlack;
    private javax.swing.JTextField jTextBoston;
    private javax.swing.JTextField jTextCarlton;
    private javax.swing.JTextField jTextCup;
    private javax.swing.JTextField jTextEsp;
    private javax.swing.JTextField jTextIceCup;
    private javax.swing.JTextField jTextIcelat;
    private javax.swing.JTextField jTextKilburn;
    private javax.swing.JTextField jTextLagos;
    private javax.swing.JTextField jTextLat;
    private javax.swing.JTextField jTextQueen;
    private javax.swing.JTextField jTextRed;
    private javax.swing.JTextField jTextcoffee;
    private javax.swing.JTextArea jTextmain;
    private javax.swing.JButton jTotal;
    private javax.swing.JLabel jlblCakes;
    private javax.swing.JLabel jlblCostCakes;
    private javax.swing.JLabel jlblCostDrinks;
    private javax.swing.JLabel jlblDrinks;
    private javax.swing.JLabel jlblService;
    private javax.swing.JLabel jlblServices;
    private javax.swing.JLabel jlblSubTotal;
    private javax.swing.JLabel jlblSubTotals;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTaxes;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JLabel jlblTotals;
    // End of variables declaration//GEN-END:variables
}
